
from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


def create_gene_report(
    gene_name,
    gene_id,
    organism,
    chromosome,
    description,
    sequence_stats=None,
    articles=None,
):
    buffer = BytesIO()

    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=0.6 * inch,
        leftMargin=0.6 * inch,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
    )

    styles = getSampleStyleSheet()
    story = []

    story.append(
        Paragraph("GeneLens AI - Gene Research Report", styles["Title"])
    )
    story.append(Spacer(1, 16))

    gene_table = [
        ["Field", "Value"],
        ["Gene symbol", str(gene_name)],
        ["NCBI Gene ID", str(gene_id)],
        ["Organism", str(organism)],
        ["Chromosome", str(chromosome)],
        ["Description", str(description)],
    ]

    table = Table(gene_table, colWidths=[1.5 * inch, 5.3 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#DDE8E0")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("PADDING", (0, 0), (-1, -1), 7),
    ]))

    story.append(Paragraph("1. Gene Information", styles["Heading2"]))
    story.append(table)
    story.append(Spacer(1, 16))

    if sequence_stats:
        story.append(
            Paragraph("2. DNA Sequence Analysis", styles["Heading2"])
        )

        stats_table = [
            ["Measurement", "Value"],
            ["Sequence length", f"{sequence_stats['length']:,} bp"],
            ["GC content", f"{sequence_stats['gc_percentage']:.2f}%"],
            ["AT content", f"{sequence_stats['at_percentage']:.2f}%"],
        ]

        story.append(Table(
            stats_table,
            colWidths=[2.5 * inch, 2.5 * inch],
            style=TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0),
                 colors.HexColor("#DDE8E0")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("PADDING", (0, 0), (-1, -1), 7),
            ]),
        ))
        story.append(Spacer(1, 16))

    if articles:
        story.append(
            Paragraph("3. Retrieved PubMed Literature", styles["Heading2"])
        )

        for article in articles[:10]:
            title = str(article.get("title", "Title unavailable"))
            year = str(article.get("year", "Year unavailable"))
            pmid = str(article.get("pmid", ""))
            url = f"https://pubmed.ncbi.nlm.nih.gov/{pmid}/" if pmid else ""

            story.append(Paragraph(
                f"<b>{title}</b> ({year})",
                styles["BodyText"]
            ))
            story.append(Paragraph(
                f"Authors: {article.get('authors', 'Unavailable')}",
                styles["BodyText"]
            ))

            if url:
                story.append(Paragraph(
                    f'<link href="{url}" color="blue">{url}</link>',
                    styles["BodyText"]
                ))

            story.append(Spacer(1, 8))

    story.append(Spacer(1, 16))
    story.append(Paragraph(
        "Generated by GeneLens AI. Verify biological interpretations "
        "against the original database records and research publications.",
        styles["Italic"],
    ))

    document.build(story)
    buffer.seek(0)

    return buffer.getvalue()